# ???????????? Spring
spring:
  # ???????????? ??????????? ? ???? ??????
  datasource:
    url: jdbc:postgresql://db:5432/tasksBase?currentSchema=tasks_schema
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  # ???????????? liquibase (????????? ??????? ??????? ? ????????? ????? ?? ?? SQL ????????)
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasks_schema
# ???????????? ???????????? Swagger (?????????? ?????? ?????? ??? ???????? ? ????????????)
springdoc:
  override-with-generic-response: false
